"""Added days for plan generation

Revision ID: 68756d721df7
Revises: 4e9cadcc4814
Create Date: 2026-07-27 12:44:13.841490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68756d721df7'
down_revision: Union[str, Sequence[str], None] = '4e9cadcc4814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plans', sa.Column('days', sa.Integer(), server_default='7', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_plans', 'days')
    # ### end Alembic commands ###
