"""add context_type and context_id to conversations

Revision ID: bdc2269234c8
Revises: be21060f5f8d
Create Date: 2026-07-27 16:20:55.657835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc2269234c8'
down_revision: Union[str, Sequence[str], None] = 'be21060f5f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('context_type', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('context_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'context_id')
    op.drop_column('conversations', 'context_type')
    # ### end Alembic commands ###
