"""add student_profiles

Revision ID: f0e61613da0c
Revises: d6aa29c65d0b
Create Date: 2026-07-25 13:12:31.961788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0e61613da0c'
down_revision: Union[str, Sequence[str], None] = 'd6aa29c65d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('goal_description', sa.Text(), nullable=False),
    sa.Column('study_hours_per_day', sa.Float(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('diagnostic_quiz', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weak_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strong_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_focus', sa.Text(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_exam_submissions_exam_id'), table_name='exam_submissions')
    op.drop_table('exam_submissions')
    op.drop_index(op.f('ix_exams_user_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chapters', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exams_pkey'))
    )
    op.create_index(op.f('ix_exams_user_id'), 'exams', ['user_id'], unique=False)
    op.create_table('exam_submissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('exam_submissions_exam_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('exam_submissions_pkey'))
    )
    op.create_index(op.f('ix_exam_submissions_exam_id'), 'exam_submissions', ['exam_id'], unique=False)
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
